# Install NodeJs using docker
---
- hosts:  webserver
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
    - name: install docker-py package
      pip: name=docker-py
     
    - name: Running the container
      docker_container:
        image: node
        ports: 80:8080
        path: docker
        state: running

    - name: Check if container is running
          shell: docker ps
    